package pkg_game;

/**
 * Who is Jack
 * 
 * Event class
 * 
 * @author LE STUM Sébastien
 * @version 2013.03.11 V1.0
 */
public enum Event
{
    NO_EVENT, GAME_OVER, CONGRATULATION, HAVE_NEWSPAPER, HAVE_SEEN_NECK, HAVE_SEEN_HAT, USE_DIARY,
    FOUND_UNKNOWN_FINGERPRINT, SPEECH_ENQUETE1, SPEECH_ENQUETE2, SPEECH_PROSTITUTE, USED_DNA_COMPARATOR,
    FOUND_HAIR, KID_INFOS, SPEECH_JACK
}
